version: "3.8"
services:
  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL

  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
